package com.evernym.agent.core


object Constants {

  val AGENT_CORE_ACTOR_SYSTEM_NAME = "agent-core"

  val ACTOR_TYPE_USER_AGENT_ACTOR = 1

  val ACTOR_TYPE_USER_AGENT_PAIRWISE_ACTOR = 2


  val MSG_TYPE_AGENT_CREATED = "AGENT_CREATED"

  val MSG_TYPE_CREATE_PAIRWISE_KEY = "CREATE_PAIRWISE_KEY"

  val MSG_TYPE_PAIRWISE_KEY_CREATED = "PAIRWISE_KEY_CREATED"
}
